"use client";

import { useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";

/* -------------------------------------------------------------------------- */
/* The map                                                                     */
/* -------------------------------------------------------------------------- */

/**
 * Outline of India, drawn here rather than pulled from a mapping library.
 *
 * It was generated by projecting a coarse list of boundary coordinates through
 * a Mercator projection and smoothing the result, which is why the coast reads
 * as a coast instead of a chain of straight segments. It is a brand map that
 * carries pins, not a survey: the northeast in particular is simplified, and no
 * boundary here should be read as a statement about a disputed one.
 */
const INDIA_PATH =
  "M168.2,31.6C177.9,30.0 187.3,32.6 194.3,36.1C201.3,39.6 215.9,49.6 218.5,56.6C221.1,63.5 214.8,79.8 212.9,85.7C211.1,91.6 206.8,94.1 205.5,99.0C204.2,103.9 202.6,116.4 203.6,121.0C204.7,125.6 209.3,128.5 212.9,131.9C216.6,135.2 226.6,140.6 229.7,144.9C232.8,149.1 234.2,156.7 235.3,162.1C236.3,167.5 234.3,179.2 237.2,183.4C240.0,187.6 249.8,188.9 255.8,191.9C261.8,194.8 273.5,201.9 280.0,204.5C286.5,207.2 296.1,208.5 302.4,210.8C308.6,213.2 318.2,218.9 324.7,221.3C331.2,223.6 342.7,226.4 348.9,227.5C355.2,228.7 365.3,229.3 369.4,229.6C373.6,229.9 377.2,232.2 378.7,229.6C380.3,227.0 378.5,214.0 380.6,210.8C382.7,207.6 392.1,205.5 393.6,206.6C395.2,207.8 390.5,217.1 391.8,219.2C393.1,221.2 398.5,221.0 403.0,221.3C407.4,221.6 418.0,221.3 423.5,221.3C428.9,221.3 438.2,221.6 442.1,221.3C446.0,221.0 450.1,222.4 451.4,219.2C452.7,216.0 448.8,203.5 451.4,198.2C454.0,192.9 463.5,185.4 470.0,181.3C476.5,177.1 490.1,170.0 498.0,168.5C505.8,167.0 519.4,168.2 525.9,170.6C532.4,173.0 540.9,182.5 544.5,185.5C548.2,188.5 551.7,187.7 552.0,191.9C552.3,196.0 549.3,211.5 546.4,215.0C543.5,218.5 536.2,215.6 531.5,217.1C526.8,218.6 517.3,221.1 512.9,225.4C508.4,229.8 502.4,242.2 499.8,248.3C497.2,254.3 497.4,262.5 494.2,268.8C491.1,275.1 480.3,286.7 477.5,293.3C474.6,299.8 475.8,311.5 473.8,315.5C471.7,319.4 464.9,323.8 462.6,321.5C460.2,319.3 460.1,302.5 457.0,299.3C453.9,296.2 442.8,302.5 440.2,299.3C437.6,296.2 436.8,282.4 438.4,277.0C439.9,271.6 454.8,263.8 451.4,260.6C448.0,257.5 419.9,257.3 414.1,254.4C408.4,251.6 413.3,242.3 410.4,240.0C407.5,237.7 397.0,235.9 393.6,237.9C390.3,239.9 388.3,250.1 386.2,254.4C384.1,258.8 378.2,265.4 378.7,268.8C379.3,272.3 387.8,275.3 389.9,279.0C392.0,282.7 393.1,288.8 393.6,295.3C394.2,301.8 398.6,320.7 393.6,325.5C388.7,330.3 364.2,325.6 358.2,329.5C352.2,333.5 353.9,348.7 350.8,353.5C347.7,358.2 341.4,359.8 335.9,363.4C330.4,367.0 318.2,373.4 311.7,379.2C305.2,385.0 295.3,399.0 289.3,404.7C283.3,410.5 274.6,416.2 268.8,420.3C263.1,424.4 253.5,430.7 248.3,433.9C243.1,437.2 234.4,439.0 231.6,443.6C228.7,448.2 227.6,459.8 227.8,466.8C228.1,473.8 233.9,486.7 233.4,493.6C232.9,500.6 225.4,509.1 224.1,516.5C222.8,524.0 225.7,540.3 224.1,546.9C222.5,553.5 217.1,560.0 212.9,563.9C208.8,567.9 198.5,571.8 194.3,575.2C190.1,578.7 186.3,587.4 183.1,588.4C180.0,589.5 175.3,587.5 171.9,582.8C168.6,578.0 162.0,562.2 158.9,554.5C155.8,546.8 153.2,535.9 149.6,527.9C145.9,520.0 137.3,506.8 132.8,497.5C128.4,488.1 120.8,468.0 117.9,461.0C115.0,454.0 114.4,453.4 112.3,447.5C110.2,441.5 105.4,428.2 103.0,418.4C100.7,408.5 97.1,386.9 95.6,377.2C94.0,367.6 92.6,356.2 91.8,349.5C91.1,342.8 91.3,331.2 90.0,329.5C88.7,327.9 86.7,335.6 82.5,337.5C78.3,339.5 65.9,343.2 60.2,343.5C54.4,343.8 46.5,343.5 41.5,339.5C36.6,335.6 25.3,320.3 24.8,315.5C24.2,310.7 34.2,307.7 37.8,305.4C41.5,303.2 51.6,301.6 50.8,299.3C50.1,297.1 37.4,290.9 32.2,289.2C27.0,287.5 17.0,288.3 13.6,287.2C10.2,286.0 7.2,283.1 8.0,281.1C8.8,279.1 14.5,274.6 19.2,272.9C23.9,271.2 36.3,275.2 41.5,268.8C46.8,262.5 50.7,237.4 56.4,227.5C62.2,217.6 76.8,206.2 82.5,198.2C88.3,190.2 93.0,176.6 97.4,170.6C101.9,164.7 110.0,160.8 114.2,155.6C118.4,150.5 125.7,139.5 127.2,134.0C128.8,128.6 126.9,121.5 125.4,116.6C123.8,111.7 116.6,103.6 116.1,99.0C115.5,94.4 121.6,89.1 121.6,83.5C121.6,77.9 115.5,63.9 116.1,58.8C116.6,53.8 118.1,51.3 125.4,47.5C132.7,43.7 158.6,33.2 168.2,31.6Z";

const MAP_VIEWBOX = { width: 560, height: 620 };

/* -------------------------------------------------------------------------- */
/* Data                                                                        */
/* -------------------------------------------------------------------------- */

type Place = {
  name: string;
  /** Where it sits, small under the name. */
  region: string;
  blurb: string;
  /** Position over the map, as a percentage of the viewBox. */
  x: number;
  y: number;
};

/**
 * Percentages come straight off the projection above, so a pin lands where the
 * place actually is rather than where it looked about right.
 */
const DESTINATIONS: Place[] = [
  {
    name: "Rishikesh",
    region: "Uttarakhand",
    blurb: "Riverside mandaps in the Himalayan foothills.",
    x: 34.93,
    y: 24.44,
  },
  {
    name: "Jaisalmer",
    region: "Rajasthan",
    blurb: "Desert camps and fort courtyards in the Thar.",
    x: 10.41,
    y: 35.32,
  },
  {
    name: "Jaipur",
    region: "Rajasthan",
    blurb: "Forts and havelis built for a baraat.",
    x: 26.68,
    y: 35.32,
  },
  {
    name: "Agra",
    region: "Uttar Pradesh",
    blurb: "Mughal gardens within sight of the Taj.",
    x: 34.06,
    y: 34.41,
  },
  {
    name: "Udaipur",
    region: "Rajasthan",
    blurb: "Lake palaces, and the wedding everyone pictures.",
    x: 19.76,
    y: 43.09,
  },
  {
    name: "Alibaug",
    region: "Maharashtra",
    blurb: "Private villas an hour by ferry from Mumbai.",
    x: 16.96,
    y: 62.3,
  },
  {
    name: "Hyderabad",
    region: "Telangana",
    blurb: "Palace banquets and a Nizami table.",
    x: 35.59,
    y: 66.28,
  },
  {
    name: "Goa",
    region: "West coast",
    blurb: "Beach ceremonies and long sunset receptions.",
    x: 20.16,
    y: 72.21,
  },
  {
    name: "Coorg",
    region: "Karnataka",
    blurb: "Coffee estates in the Western Ghats.",
    x: 26.48,
    y: 81.96,
  },
  {
    name: "Alleppey",
    region: "Kerala",
    blurb: "Backwater houseboats and the Kerala coast.",
    x: 28.51,
    y: 90.65,
  },
];

/** Mumbai, where every market below sits. */
const MUMBAI = { x: 16.86, y: 61.1 };

/**
 * The markets are a few kilometres apart, which on a map of a country this size
 * puts all three inside a fifth of one percent of the width: they would print
 * on top of each other. So the pins are fanned out to a legible radius around
 * Mumbai and tethered back to it with a hairline. The cluster is deliberately
 * not to scale, and the anchor is drawn so that reads as intentional.
 */
const MARKET_FAN_RADIUS = 9;

const MARKETS: Place[] = [
  {
    name: "Zaveri Bazaar",
    region: "Kalbadevi",
    blurb: "The gold market. Bridal sets, bangles and chains.",
    ...fan(305),
  },
  {
    name: "Dadar",
    region: "Central Mumbai",
    blurb: "The flower market, busiest at four in the morning.",
    ...fan(5),
  },
  {
    name: "Santacruz",
    region: "Western suburbs",
    blurb: "Fabric, tailoring and trousseau shopping.",
    ...fan(65),
  },
];

/** Puts a pin on a circle around Mumbai, correcting for the viewBox aspect. */
function fan(degrees: number) {
  const radians = (degrees * Math.PI) / 180;
  const aspect = MAP_VIEWBOX.width / MAP_VIEWBOX.height;
  return {
    x: MUMBAI.x + Math.cos(radians) * MARKET_FAN_RADIUS,
    y: MUMBAI.y + Math.sin(radians) * MARKET_FAN_RADIUS * aspect,
  };
}

const TABS = [
  { id: "destinations", label: "Destinations", places: DESTINATIONS },
  { id: "markets", label: "Markets", places: MARKETS },
] as const;

type TabId = (typeof TABS)[number]["id"];

/* -------------------------------------------------------------------------- */
/* Pieces                                                                      */
/* -------------------------------------------------------------------------- */

/** A teardrop marker whose tip, not its centre, sits on the coordinate. */
function PinGlyph() {
  return (
    <svg
      viewBox="0 0 24 34"
      aria-hidden="true"
      focusable="false"
      className="h-7 w-5 drop-shadow-[0_3px_6px_rgba(0,0,0,0.45)] md:h-8 md:w-6"
    >
      <path
        d="M12 33.5C12 33.5 23 20.5 23 12A11 11 0 1 0 1 12c0 8.5 11 21.5 11 21.5Z"
        fill="var(--color-ivory)"
        stroke="rgba(74,15,40,0.55)"
        strokeWidth="1.2"
      />
      <circle cx="12" cy="12" r="4.2" fill="#a31a57" />
    </svg>
  );
}

export default function InteractiveMap() {
  const [tab, setTab] = useState<TabId>("destinations");
  const reduceMotion = useReducedMotion();

  const active = TABS.find((entry) => entry.id === tab) ?? TABS[0];
  const showingMarkets = tab === "markets";

  // With motion reduced the pins still arrive, they just fade rather than drop.
  const pinFrom = reduceMotion
    ? { opacity: 0, y: 0, scale: 1 }
    : { opacity: 0, y: -28, scale: 0.6 };

  return (
    <section className="relative w-full py-20 md:py-28" aria-labelledby="map-heading">
      <div className="mx-auto max-w-6xl px-6 md:px-8">
        {/* Heading and toggle share a row from sm up, so the pill sits top right. */}
        <div className="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between">
          <div className="max-w-xl">
            <h2
              id="map-heading"
              className="font-serif-display text-3xl font-medium text-ivory sm:text-4xl"
            >
              Where India gets married
            </h2>
            <p className="mt-4 font-body text-base font-light leading-relaxed text-ivory/85">
              The places couples travel to, and the markets they shop in before
              they go. Switch between the two.
            </p>
          </div>

          {/* Pill toggle. A tablist, so arrow keys and screen readers both work. */}
          <div
            role="tablist"
            aria-label="Map view"
            className="flex shrink-0 rounded-full border border-white/25 bg-white/10 p-1 backdrop-blur-md"
          >
            {TABS.map((entry) => {
              const selected = entry.id === tab;
              return (
                <button
                  key={entry.id}
                  type="button"
                  role="tab"
                  aria-selected={selected}
                  onClick={() => setTab(entry.id)}
                  className="relative rounded-full px-5 py-2.5 font-body text-sm font-semibold transition-colors duration-200 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ivory"
                >
                  {/* One shared element slides between the two, rather than two
                      backgrounds cross-fading. */}
                  {selected && (
                    <motion.span
                      layoutId="map-toggle-thumb"
                      className="absolute inset-0 rounded-full bg-ivory"
                      transition={
                        reduceMotion
                          ? { duration: 0 }
                          : { type: "spring", stiffness: 420, damping: 36 }
                      }
                    />
                  )}
                  <span
                    className={`relative z-10 ${selected ? "text-maroon" : "text-ivory/80"}`}
                  >
                    {entry.label}
                  </span>
                </button>
              );
            })}
          </div>
        </div>

        <div className="mt-12 grid items-center gap-10 lg:grid-cols-[1.05fr_1fr] lg:gap-14">
          {/* ------------------------------------------------------------ map */}
          <div className="relative mx-auto w-full max-w-[22rem] sm:max-w-[24rem] lg:max-w-[26rem]">
            <svg
              viewBox={`0 0 ${MAP_VIEWBOX.width} ${MAP_VIEWBOX.height}`}
              className="block h-auto w-full"
              role="img"
              aria-label="Map of India"
            >
              <path
                d={INDIA_PATH}
                fill="#FDF6E3"
                stroke="rgba(74,15,40,0.35)"
                strokeWidth="2"
                strokeLinejoin="round"
              />
            </svg>

            {/* Pins ride above the map in their own percentage-positioned layer,
                so they never distort with the viewBox. */}
            <div className="pointer-events-none absolute inset-0">
              {showingMarkets && (
                <>
                  {/* Hairlines back to Mumbai, so the fan reads as one place. */}
                  <svg
                    viewBox={`0 0 ${MAP_VIEWBOX.width} ${MAP_VIEWBOX.height}`}
                    className="absolute inset-0 h-full w-full"
                    aria-hidden="true"
                  >
                    {MARKETS.map((place) => (
                      <line
                        key={place.name}
                        x1={(MUMBAI.x / 100) * MAP_VIEWBOX.width}
                        y1={(MUMBAI.y / 100) * MAP_VIEWBOX.height}
                        x2={(place.x / 100) * MAP_VIEWBOX.width}
                        y2={(place.y / 100) * MAP_VIEWBOX.height}
                        stroke="rgba(74,15,40,0.55)"
                        strokeWidth="1.5"
                        strokeDasharray="4 4"
                      />
                    ))}
                  </svg>

                  <span
                    className="absolute h-2.5 w-2.5 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#a31a57] ring-4 ring-[#a31a57]/25"
                    style={{ left: `${MUMBAI.x}%`, top: `${MUMBAI.y}%` }}
                  />
                  <span
                    className="absolute -translate-y-1/2 translate-x-3 font-body text-[0.65rem] font-semibold tracking-[0.14em] text-maroon uppercase md:text-xs"
                    style={{ left: `${MUMBAI.x}%`, top: `${MUMBAI.y}%` }}
                  >
                    Mumbai
                  </span>
                </>
              )}

              {/* Keyed on the tab, so switching drops a fresh set in. */}
              <AnimatePresence mode="wait">
                <motion.div key={tab} className="absolute inset-0">
                  {active.places.map((place, index) => (
                    <motion.span
                      key={place.name}
                      className="absolute -translate-x-1/2"
                      style={{
                        left: `${place.x}%`,
                        top: `${place.y}%`,
                        // The glyph's tip is at its bottom edge, so the whole
                        // pin is lifted clear of the point it marks.
                        transform: "translate(-50%, -100%)",
                      }}
                      initial={pinFrom}
                      animate={{ opacity: 1, y: 0, scale: 1 }}
                      exit={reduceMotion ? { opacity: 0 } : { opacity: 0, scale: 0.6 }}
                      transition={
                        reduceMotion
                          ? { duration: 0.2, delay: index * 0.02 }
                          : {
                              type: "spring",
                              stiffness: 520,
                              damping: 24,
                              delay: index * 0.07,
                            }
                      }
                    >
                      <PinGlyph />
                    </motion.span>
                  ))}
                </motion.div>
              </AnimatePresence>
            </div>
          </div>

          {/* ----------------------------------------------------------- list */}
          <div>
            <AnimatePresence mode="wait">
              <motion.ul
                key={tab}
                className={`m-0 grid list-none grid-cols-1 gap-x-8 p-0 ${
                  active.places.length > 4 ? "sm:grid-cols-2" : ""
                }`}
                initial={reduceMotion ? { opacity: 0 } : { opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                exit={reduceMotion ? { opacity: 0 } : { opacity: 0, y: -12 }}
                transition={{ duration: 0.3, ease: "easeOut" }}
              >
                {active.places.map((place, index) => (
                  <motion.li
                    key={place.name}
                    className="border-b border-white/10 py-3 last:border-b-0"
                    initial={reduceMotion ? { opacity: 0 } : { opacity: 0, x: -14 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{
                      duration: 0.35,
                      delay: index * 0.05,
                      ease: "easeOut",
                    }}
                  >
                    <p className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
                      <span className="font-serif-display text-xl font-medium text-ivory md:text-2xl">
                        {place.name}
                      </span>
                      <span className="font-body text-xs tracking-[0.14em] text-ivory/60 uppercase">
                        {place.region}
                      </span>
                    </p>
                    <p className="mt-1 font-body text-sm leading-relaxed text-ivory/80">
                      {place.blurb}
                    </p>
                  </motion.li>
                ))}
              </motion.ul>
            </AnimatePresence>

            {showingMarkets && (
              <p className="mt-5 font-body text-xs leading-relaxed text-ivory/55">
                All three are in Mumbai and sit within a few kilometres of each
                other. The pins are spread out so they can be told apart, so the
                cluster is not to scale.
              </p>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}
